import Head from 'next/head'
import { ProgramPreview } from '../components/ProgramPreview'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Program Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-xl m-auto">
        <ProgramPreview />
      </main>
    </div>
  )
}
