import Head from 'next/head'
import Image from 'next/image'
import { ProgramPreview } from '../components/ProgramPreview'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Program Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-xl m-auto">
        <ProgramPreview />
      </main>
    </div>
  )
}
